CREATE DATABASE RandomPicker;
USE RandomPicker;

CREATE USER ''@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON RandomPicker.* TO ''@'%';
FLUSH PRIVILEGES;

CREATE TABLE users(
id INT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(50) UNIQUE NOT NULL,
password_hash VARCHAR(255) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE wheels(
id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(50) NOT NULL,
user_id INT,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE items(
id INT PRIMARY KEY AUTO_INCREMENT,
label VARCHAR(50) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
wheel_id INT,
FOREIGN KEY (wheel_id) REFERENCES wheels(id) ON DELETE CASCADE
);

SELECT * FROM users;

SELECT title FROM wheels;
